<?php /** @var TrustMate\Opinions\Block\Shop $block **/ ?>

<?php if ($block->isWidgetEnabled() && $block->getWidgetLink()): ?>
    <?php $location = $block->getShopWidgetLocation(); ?>

    <div id='TRUST_MATE_MODAL_REVIEW_BUTTON_WIDGET'></div>

    <script type='text/javascript'
            id='TRUST_MATE_MODAL_REVIEW_BUTTON_SCRIPT_ID'
            data-config='{"behaviour":{"widgetPlacement":"<?= $location ?>"},"view":{}}'
            data-env='{"host":"https://trustmate.io"}'
            src="<?= $block->getWidgetLink() ?>"
    ></script>
<?php endif; ?>