<?php

use Magento\Framework\Escaper;
use TrustMate\Opinions\Block\Product\View\ListView;

/**
 * @var Escaper $escaper
 * @var ListView $block
 */

$reviewsCollection = $block->getReviewsCollection();
$items = $reviewsCollection->getItems();
$format = $block->getDateFormat() ?: IntlDateFormatter::SHORT;

if ($items !== null):
    if (count($items)): ?>
        <div class="block review-list" id="customer-reviews">
            <div class="block-title">
                <strong>
                    <?= /* @escapeNotVerified */ __('Customer Reviews') ?>
                </strong>
            </div>
            <div class="block-content">
                <div class="toolbar review-toolbar">
                    <?= $block->getChildHtml('toolbar') ?>
                </div>
                <ol class="items review-items">
                    <?php foreach ($items as $review):
                        if ($review->getStatus() === '1' || $review->getStatus() === null) : ?>
                            <li class="item review-item <?php if ($block->isTrustMateOpinion($review)): ?> trustmate-opinion <?php endif; ?>"
                                itemscope itemprop="review" itemtype="http://schema.org/Review">
                                <?php if ($block->isTrustMateOpinion($review)):
                                    $imageName = (strtolower($review->getLanguage()) === 'pl')
                                        ? 'trustmate_confirmed_pl.png'
                                        : 'trustmate_confirmed_en.png';
                                    ?>
                                    <img class="trustmate-badge"
                                         src="<?= $block->getViewFileUrl('TrustMate_Opinions/images/' . $imageName); ?>"
                                         alt="<?= $escaper->escapeHtml($review->getTitle()) ?>">
                                <?php endif; ?>
                                <div class="review-title"
                                     itemprop="name"><?= $escaper->escapeHtml($review->getTitle()) ?></div>
                                <?php if ($block->isTrustMateOpinion($review)): ?>
                                    <div class="rating-summary item" itemprop="reviewRating" itemscope
                                         itemtype="http://schema.org/Rating">
                                        <div class="rating-result" title="
                                                    <?= /* @escapeNotVerified */ $review->getPercent() ?>%">
                                            <meta itemprop="worstRating" content="1"/>
                                            <meta itemprop="bestRating" content="100"/>
                                            <span style="width:
                                            <?= /* @escapeNotVerified */ $review->getPercent() ?>%">
                                                            <span itemprop="ratingValue">
                                                                <?= /* @escapeNotVerified */
                                                                $review->getPercent() ?>%
                                                            </span>
                                                        </span>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <?php if (is_countable($review->getRatingVotes())) :
                                    if (count($review->getRatingVotes())): ?>
                                        <div class="review-ratings">
                                            <?php foreach ($review->getRatingVotes() as $_vote): ?>
                                                <div class="rating-summary item" itemprop="reviewRating" itemscope
                                                     itemtype="http://schema.org/Rating">
                                                    <span class="label rating-label">
                                                        <span>
                                                            <?= $escaper->escapeHtml($_vote->getRatingCode()) ?>
                                                        </span>
                                                    </span>
                                                    <div class="rating-result" title="
                                                    <?= /* @escapeNotVerified */ $_vote->getPercent() ?>%">
                                                        <meta itemprop="worstRating" content="1"/>
                                                        <meta itemprop="bestRating" content="100"/>
                                                        <span style="width:
                                                        <?= /* @escapeNotVerified */ $_vote->getPercent() ?>%">
                                                            <span itemprop="ratingValue">
                                                                <?= /* @escapeNotVerified */
                                                                $_vote->getPercent() ?>%
                                                            </span>
                                                        </span>
                                                    </div>
                                                </div>
                                            <?php endforeach; ?>
                                        </div>
                                    <?php endif;
                                endif; ?>
                                <div class="review-content" itemprop="description">
                                    <?= nl2br($escaper->escapeHtml($review->getDetail())) ?>
                                </div>
                                <div class="review-details">
                                    <p class="review-author">
                                    <span class="review-details-label">
                                        <?= /* @escapeNotVerified */
                                        __('Review by') ?>
                                    </span>
                                        <strong class="review-details-value" itemprop="author">
                                            <?= $escaper->escapeHtml($review->getNickname()) ?>
                                        </strong>
                                    </p>
                                    <p class="review-date">
                                        <span class="review-details-label"><?= /* @escapeNotVerified */
                                            __('Posted on') ?></span>
                                        <time class="review-details-value" itemprop="datePublished" datetime="
                                    <?= /* @escapeNotVerified */
                                        $block->formatDate($review->getCreatedAt(), $format) ?>">
                                            <?= /* @escapeNotVerified */
                                            $block->formatDate($review->getCreatedAt(), $format) ?>
                                        </time>
                                    </p>
                                </div>
                            </li>
                        <?php endif;
                    endforeach; ?>
                </ol>
                <div class="toolbar review-toolbar">
                    <?= $block->getChildHtml('toolbar') ?>
                </div>
            </div>
        </div>
    <?php endif;
endif; ?>
