<?php

use TrustMate\Opinions\Block\Product\View\ListView;

/**
 * @var ListView $block
 */

$reviewsCollection = $block->getReviewsCollection();
$_items = null;
if ($reviewsCollection) {
    $_items = $block->getReviewsCollection()->getItems();
}

$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;

if ($_items !== null):
    if (count($_items)):
?>
        <div class="block review-list" id="customer-reviews">
            <div class="block-title">
                <strong><?php /* @escapeNotVerified */ echo __('Customer Reviews') ?></strong>
            </div>
            <div class="block-content">
                <div class="toolbar review-toolbar">
                    <?php echo $block->getChildHtml('toolbar') ?>
                </div>
                <ol class="items review-items">
                    <?php foreach ($_items as $_review): ?>
                        <li class="item review-item <?php if ($block->isTrustMateOpinion($_review)): ?>trustmate-opinion<?php endif; ?>" itemscope itemprop="review" itemtype="http://schema.org/Review">
                            <?php if ($block->isTrustMateOpinion($_review)):
                                $imageName = (strtolower($_review->getLanguage()) === 'pl')
                                    ? 'trustmate_confirmed_pl.png'
                                    : 'trustmate_confirmed_en.png';
                            ?>
                                <img class="trustmate-badge"
                                     src="<?= $block->getViewFileUrl('TrustMate_Opinions/images/' . $imageName); ?>"
                                     alt="<?= $block->escapeHtml($_review->getTitle()) ?>">
                            <?php endif; ?>
                            <div class="review-title" itemprop="name"><?php echo $block->escapeHtml($_review->getTitle()) ?></div>
                            <?php
                            if (is_countable($_review->getRatingVotes())) :
                                if (count($_review->getRatingVotes())):
                            ?>
                                <div class="review-ratings">
                                    <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                                        <div class="rating-summary item" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                                            <span class="label rating-label"><span><?php echo $block->escapeHtml($_vote->getRatingCode()) ?></span></span>
                                            <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
                                                <meta itemprop="worstRating" content = "1"/>
                                                <meta itemprop="bestRating" content = "100"/>
                                                <span style="width:<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
                                    <span itemprop="ratingValue"><?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%</span>
                                </span>
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                            <?php
                                endif;
                            endif; ?>
                            <div class="review-content" itemprop="description">
                                <?php echo nl2br($block->escapeHtml($_review->getDetail())) ?>
                            </div>
                            <div class="review-details">
                                <p class="review-author">
                                    <span class="review-details-label"><?php /* @escapeNotVerified */ echo __('Review by')?></span>
                                    <strong class="review-details-value" itemprop="author"><?php echo $block->escapeHtml($_review->getNickname()) ?></strong>
                                </p>
                                <p class="review-date">
                                    <span class="review-details-label"><?php /* @escapeNotVerified */ echo __('Posted on') ?></span>
                                    <time class="review-details-value" itemprop="datePublished" datetime="<?php /* @escapeNotVerified */ echo $block->formatDate($_review->getCreatedAt(), $format) ?>"><?php /* @escapeNotVerified */ echo $block->formatDate($_review->getCreatedAt(), $format) ?></time>
                                </p>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ol>
                <div class="toolbar review-toolbar">
                    <?php echo $block->getChildHtml('toolbar') ?>
                </div>
            </div>
        </div>
<?php
    endif;
endif;
?>
